version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runscript add_data && python manage.py test && python manage.py runserver 0.0.0.0:8000"
    container_name: task
    ports:
      - "8000:8000"